const $ = (s, p = document) => p.querySelector(s);
const root = $('#page-root');
const reports = [
  ['⚡','Apple AirPods Pro','White AirPods in a black case with a small sticker','Library','Electronics','Jul 24, 2026','lost'],
  ['🪪','Student ID Card','Found near the billing counter, name visible on card','Canteen','ID Cards','Jul 23, 2026','found'],
  ['🎒','Blue Backpack','Navy blue Nike backpack with laptop compartment','Classroom B-204','Bags & Backpacks','Jul 22, 2026','returned'],
  ['🔑','Bunch of Keys','3 keys on a red keychain ring','Parking Area','Keys','Jul 22, 2026','found'],
  ['💧','Steel Water Bottle','Silver reusable bottle with black cap','Gym','Personal Items','Jul 21, 2026','found'],
  ['📱','Phone Charger','White Type-C charger and cable','Computer Lab','Electronics','Jul 20, 2026','lost']
];
const itemCard = (r) => `<article class="card item-card"><div class="item-image ${r[6]}"><span class="badge ${r[6]}">${r[6][0].toUpperCase()+r[6].slice(1)}</span>${r[0]}</div><div class="item-content"><h3>${r[1]}</h3><p>${r[2]}</p><div class="place">${r[3]}</div><div class="meta"><span class="tag">${r[4]}</span><span>${r[5]}</span></div></div></article>`;
const shell = (body, cls='') => `<div class="page ${cls}">${body}</div>`;
function home(){root.innerHTML=shell(`<div class="hero"><span class="eyebrow">189 active reports right now</span><h1>Lost something?<span class="gradient-text">Find it with NexusFind</span></h1><p class="lead">Your college's smart lost & found system. Report lost items, browse found items, and get reunited — fast.</p><div class="action-row"><button class="button go" data-go="lost">📋 &nbsp; Report Lost Item</button><button class="button outline go" data-go="found">✅ &nbsp; Report Found Item</button></div><label class="search">🔍 <input id="homeSearch" placeholder="Search for lost or found items..." /></label></div><div class="stats"><div class="stat-card"><span class="icon">📋</span><strong>1,284</strong><small>Items Reported</small></div><div class="stat-card"><span class="icon">✅</span><strong>847</strong><small>Items Found</small></div><div class="stat-card"><span class="icon">🎉</span><strong>612</strong><small>Returned</small></div><div class="stat-card"><span class="icon">⌛</span><strong>189</strong><small>Active Reports</small></div></div><div class="section-heading"><div><h2>Recent Reports</h2><p>Latest activity from campus</p></div><button class="small-button go" data-go="browse">View All Items →</button></div><div class="items-grid">${reports.slice(0,4).map(itemCard).join('')}</div><div class="how-it-works"><h2>How It Works</h2><p>Simple 3-step process to recover your items</p><div class="steps"><div class="step-card"><div class="emoji">📝</div><small>STEP 01</small><h3>Report Your Item</h3></div><div class="step-card"><div class="emoji">🔍</div><small>STEP 02</small><h3>Smart Matching</h3></div><div class="step-card"><div class="emoji">🔔</div><small>STEP 03</small><h3>Get Connected</h3></div></div></div>`,'home');}
function browse(){root.innerHTML=shell(`<h1 class="page-title">Browse Lost & Found</h1><p class="subtitle">Search active campus reports by item type, category, and location</p><div class="filters"><div class="field"><label>Search</label><label class="search"><span>🔍</span><input id="browseSearch" placeholder="e.g. Laptop, Keys..." /></label></div><div class="field"><label>Type</label><select id="typeFilter"><option value="all">All Types</option><option value="lost">Lost</option><option value="found">Found</option><option value="returned">Returned</option></select></div><div class="field"><label>Category</label><select><option>All Categories</option><option>Electronics</option><option>Keys</option></select></div><div class="field"><label>Location</label><select><option>All Locations</option><option>Library</option><option>Canteen</option></select></div></div><div class="browse-bar"><span>Showing <b id="resultCount">${reports.length}</b> results</span><div class="tabs"><button class="tab active" data-filter="all">All Types</button><button class="tab" data-filter="lost">Lost</button><button class="tab" data-filter="found">Found</button><button class="tab" data-filter="returned">Returned</button></div></div><div class="items-grid browse-grid" id="browseGrid">${reports.map(itemCard).join('')}</div>`);bindBrowse()}
function reportHeader(kind){return `<div class="form-header"><h1>${kind==='lost'?'🔴 Report a Lost Item':'<span class="eyebrow found-label">FOUND SOMETHING?</span><br>Help return a <span class="gradient-text inline">found item</span>'}</h1><p>${kind==='lost'?'Help us help you find your missing item':'Take 30 seconds to log the item — a fellow student will thank you.'}</p></div>`}
function lost(){root.innerHTML=shell(`${reportHeader('lost')}<div class="progress" id="progress"><div class="progress-step active"><span class="progress-dot">1</span>Item Details</div><div class="progress-line"></div><div class="progress-step"><span class="progress-dot">2</span>Location & Date</div><div class="progress-line"></div><div class="progress-step"><span class="progress-dot">3</span>Contact Info</div></div><form class="form-card" id="lostForm"></form>`,'form-page');renderLostStep(1)}
function legacyRenderLostStep(step){const form=$('#lostForm');const fields= step===1?`<div class="field wide"><label>Item Name</label><input class="input" placeholder="e.g. Earphones, Keys, Wallet..." required></div><div class="field wide"><label>Category</label><select><option>Select category</option><option>Electronics</option><option>Keys</option></select></div><div class="field wide"><label>Description</label><textarea placeholder="Describe distinguishing features..."></textarea></div><div class="field wide"><label>Reward (Optional)</label><input class="input" placeholder="e.g. ₹500"></div>`:step===2?`<div class="field wide"><label>Last Seen Location</label><select><option>Select location</option><option>Library</option><option>Classroom</option></select></div><div class="field wide"><label>Specific Landmark / Area</label><input class="input" placeholder="e.g. Near window seat, 2nd floor..."></div><div class="field wide"><label>Date Lost</label><input type="date" class="input"></div><div class="hint">💡 &nbsp; The more precise your location, the higher the chance of a match.</div>`:`<div class="field wide"><label>Your Name</label><input class="input" placeholder="Full name" required></div><div class="field wide"><label>College Email</label><input type="email" class="input" placeholder="you@college.edu" required></div><div class="field wide"><label>Phone Number</label><input class="input" placeholder="+91 98765 43210"></div><div class="summary"><strong>REPORT SUMMARY</strong>Item: —<br>Category: —<br>Location: —<br>Date: —</div>`;form.innerHTML=`<div class="form-grid">${fields}</div><div class="form-actions">${step>1?'<button type="button" class="back" id="prev">← Back</button>':'<span></span>'}<button class="button" type="submit">${step===3?'Submit Report':'Continue →'}</button></div>`;[...document.querySelectorAll('.progress-step')].forEach((el,i)=>{el.classList.toggle('active',i===step-1);el.classList.toggle('done',i<step-1);el.querySelector('.progress-dot').textContent=i<step-1?'✓':i+1});[...document.querySelectorAll('.progress-line')].forEach((el,i)=>el.classList.toggle('done',i<step-1));form.onsubmit=e=>{e.preventDefault();if(step===3){toast('Your lost item report was submitted!');home();setActive('home')}else renderLostStep(step+1)};const prev=$('#prev');if(prev)prev.onclick=()=>renderLostStep(step-1)}
function legacyFound(){root.innerHTML=shell(`${reportHeader('found')}<form class="form-card" id="foundForm"><div class="form-grid"><div class="field"><label>Item Name</label><input class="input" placeholder="e.g. Silver water bottle" required></div><div class="field"><label>Category</label><select><option>Select category</option><option>Electronics</option></select></div><div class="field wide"><label>Description</label><textarea placeholder="Describe distinguishing features..."></textarea></div><div class="field wide"><label>Upload Image</label><label class="upload"> <span><span class="upload-icon">⇧</span><b>Click to upload · PNG, JPG up to 5MB</b></span><input type="file" hidden></label></div><div class="field"><label>Location Found</label><input class="input" placeholder="e.g. Cafeteria"></div><div class="field"><label>Date Found</label><input type="date" class="input"></div><div class="field wide"><label>Current Storage Location</label><input class="input" placeholder="e.g. Security desk, Block A"></div></div><div class="form-actions"><span></span><button class="button">Submit found item</button></div></form>`,'form-page');$('#foundForm').onsubmit=e=>{e.preventDefault();toast('Thank you for reporting this found item!');home();setActive('home')}}
function notifications(){const notes=[['🎯','Potential match found!','Your lost AirPods Pro report matches a found item submitted at the Library today.','2 hours ago',true],['✅','Item status updated','The Blue Backpack (NF-2026-4821) has been marked as Returned.','5 hours ago',true],['🔑','New found item near your area','A bunch of keys was found in the Parking Area — matches your search for "keys".','Yesterday, 3:12 PM',true],['📋','Report submitted successfully','Your lost item report for "Wired Earphones" (NF-2026-3917) was received.','Jul 24, 2026',false],['🏛️','Admin note on your report','Staff has reviewed your report. Please visit the security desk with your ID to claim the item.','Jul 23, 2026',false]];root.innerHTML=shell(`<div class="notification-toolbar"><div><h1 class="page-title">Notifications</h1><p class="subtitle"><b>3</b> unread notifications</p></div><div class="tabs"><button class="tab active">All</button><button class="tab">Unread</button></div></div><div class="notification-list">${notes.map(n=>`<article class="notification ${n[4]?'':'read'}"><div class="notice-icon">${n[0]}</div><div class="notice-copy"><h3>${n[1]}</h3><p>${n[2]}</p></div><time class="notice-time ${n[4]?'unread':''}">${n[3]}</time></article>`).join('')}</div>`)}
const pages={home,browse,lost,found,notifications};function setActive(page){document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page));}
function render(page){pages[page]();setActive(page);$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});bindGo()}
function bindGo(){document.querySelectorAll('.go').forEach(b=>b.onclick=()=>render(b.dataset.go));const hs=$('#homeSearch');if(hs)hs.onkeydown=e=>{if(e.key==='Enter')render('browse')}}
function bindBrowse(){let f='all';const apply=()=>{const q=$('#browseSearch').value.toLowerCase();const t=$('#typeFilter').value;const view=reports.filter(r=>(f==='all'||r[6]===f)&&(t==='all'||r[6]===t)&&r.slice(1,5).join(' ').toLowerCase().includes(q));$('#browseGrid').innerHTML=view.map(itemCard).join('');$('#resultCount').textContent=view.length};$('#browseSearch').oninput=apply;$('#typeFilter').onchange=apply;document.querySelectorAll('.tab[data-filter]').forEach(b=>b.onclick=()=>{f=b.dataset.filter;document.querySelectorAll('.tab[data-filter]').forEach(x=>x.classList.toggle('active',x===b));apply()})}
let lostDraft = {};

function renderLostStep(step) {
  const form = $('#lostForm');
  const fields = step === 1
    ? `<div class="form-grid"><div class="field wide"><label>Item Name</label><input class="input" id="lostItemName" value="${lostDraft.itemName || ''}" placeholder="e.g. Earphones, Keys, Wallet..." required></div><div class="field wide"><label>Category</label><select id="lostCategory" required><option value="">Select category</option><option>Electronics</option><option>Keys</option><option>Bags & Backpacks</option><option>ID Cards</option><option>Personal Items</option></select></div><div class="field wide"><label>Description</label><textarea id="lostDescription" placeholder="Describe distinguishing features..." required>${lostDraft.description || ''}</textarea></div><div class="field wide"><label>Reward (Optional)</label><input class="input" id="lostReward" value="${lostDraft.reward || ''}" placeholder="e.g. ₹500"></div></div>`
    : step === 2
      ? `<div class="form-grid"><div class="field wide"><label>Last Seen Location</label><select id="lostLocation" required><option value="">Select location</option><option>Library</option><option>Canteen</option><option>Classroom</option><option>Parking Area</option><option>Computer Lab</option></select></div><div class="field wide"><label>Specific Landmark / Area</label><input class="input" id="lostLandmark" value="${lostDraft.landmark || ''}" placeholder="e.g. Near window seat, 2nd floor..."></div><div class="field wide"><label>Date Lost</label><input type="date" class="input" id="lostDate" value="${lostDraft.dateLost || ''}" required></div><div class="hint">💡 &nbsp; The more precise your location, the higher the chance of a match.</div></div>`
      : `<div class="form-grid"><div class="field wide"><label>Your Name</label><input class="input" id="lostName" value="${lostDraft.name || ''}" placeholder="Full name" required></div><div class="field wide"><label>College Email</label><input type="email" class="input" id="lostEmail" value="${lostDraft.email || ''}" placeholder="you@college.edu" required></div><div class="field wide"><label>Phone Number</label><input class="input" id="lostPhone" value="${lostDraft.phone || ''}" placeholder="+91 98765 43210" required></div><div class="summary"><strong>REPORT SUMMARY</strong>Item: ${lostDraft.itemName || '—'}<br>Category: ${lostDraft.category || '—'}<br>Location: ${lostDraft.location || '—'}<br>Date: ${lostDraft.dateLost || '—'}</div></div>`;
  form.innerHTML = `${fields}<div class="form-actions">${step > 1 ? '<button type="button" class="back" id="prev">← Back</button>' : '<span></span>'}<button class="button" type="submit">${step === 3 ? 'Submit Report' : 'Continue →'}</button></div>`;
  if (step === 1) $('#lostCategory').value = lostDraft.category || '';
  if (step === 2) $('#lostLocation').value = lostDraft.location || '';
  [...document.querySelectorAll('.progress-step')].forEach((el, i) => { el.classList.toggle('active', i === step - 1); el.classList.toggle('done', i < step - 1); el.querySelector('.progress-dot').textContent = i < step - 1 ? '✓' : i + 1; });
  [...document.querySelectorAll('.progress-line')].forEach((el, i) => el.classList.toggle('done', i < step - 1));
  form.onsubmit = async (event) => {
    event.preventDefault();
    if (step === 1) Object.assign(lostDraft, { itemName: $('#lostItemName').value, category: $('#lostCategory').value, description: $('#lostDescription').value, reward: $('#lostReward').value });
    if (step === 2) Object.assign(lostDraft, { location: $('#lostLocation').value, landmark: $('#lostLandmark').value, dateLost: $('#lostDate').value });
    if (step === 3) Object.assign(lostDraft, { name: $('#lostName').value, email: $('#lostEmail').value, phone: $('#lostPhone').value });
    if (!form.checkValidity()) { form.reportValidity(); return; }
    if (step < 3) { renderLostStep(step + 1); return; }
    const submitButton = $('button[type="submit"]', form); submitButton.disabled = true; submitButton.textContent = 'Submitting...';
    try {
      await window.NexusFind.createItemReport({ ...lostDraft, type: 'lost' });
      toast('Your lost item report was submitted!'); lostDraft = {}; home(); setActive('home'); bindGo();
    } catch (error) { toast(error.message || 'Unable to submit your report. Please try again.'); submitButton.disabled = false; submitButton.textContent = 'Submit Report'; }
  };
  const previous = $('#prev'); if (previous) previous.onclick = () => renderLostStep(step - 1);
}

function found() {
  root.innerHTML = shell(`${reportHeader('found')}<form class="form-card" id="foundForm"><div class="form-grid"><div class="field"><label>Item Name</label><input class="input" id="foundItemName" placeholder="e.g. Silver water bottle" required></div><div class="field"><label>Category</label><select id="foundCategory" required><option value="">Select category</option><option>Electronics</option><option>Keys</option><option>Bags & Backpacks</option><option>ID Cards</option><option>Personal Items</option></select></div><div class="field wide"><label>Description</label><textarea id="foundDescription" placeholder="Describe distinguishing features..." required></textarea></div><div class="field wide"><label>Upload Image</label><label class="upload"><span><span class="upload-icon">⇧</span><b>Click to upload · PNG, JPG up to 5MB</b></span><input id="foundImage" type="file" accept="image/png,image/jpeg,image/webp" hidden></label></div><div class="field"><label>Location Found</label><input class="input" id="foundLocation" placeholder="e.g. Cafeteria" required></div><div class="field"><label>Date Found</label><input type="date" class="input" id="foundDate" required></div><div class="field wide"><label>Current Storage Location</label><input class="input" id="foundStorage" placeholder="e.g. Security desk, Block A" required></div></div><div class="form-actions"><span></span><button class="button" type="submit">Submit found item</button></div></form>`, 'form-page');
  const form = $('#foundForm'); const imageInput = $('#foundImage');
  imageInput.onchange = () => { if (imageInput.files[0]) toast(`Selected: ${imageInput.files[0].name}`); };
  form.onsubmit = async (event) => {
    event.preventDefault(); if (!form.checkValidity()) { form.reportValidity(); return; }
    const submitButton = $('button[type="submit"]', form); submitButton.disabled = true; submitButton.textContent = 'Uploading...';
    try {
      await window.NexusFind.createItemReport({ type: 'found', itemName: $('#foundItemName').value, category: $('#foundCategory').value, description: $('#foundDescription').value, location: $('#foundLocation').value, dateFound: $('#foundDate').value, storageLocation: $('#foundStorage').value }, imageInput.files[0] || null);
      toast('Thank you for reporting this found item!'); home(); setActive('home'); bindGo();
    } catch (error) { toast(error.message || 'Unable to submit your report. Please try again.'); submitButton.disabled = false; submitButton.textContent = 'Submit found item'; }
  };
}

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>render(b.dataset.page));function toggleTheme(){const light=document.body.dataset.theme==='light';document.body.dataset.theme=light?'':'light';localStorage.nexusTheme=light?'dark':'light';document.querySelectorAll('#themeToggle span').forEach(s=>s.textContent=light?'Light mode':'Dark mode')}$('#themeToggle').onclick=toggleTheme;$('#mobileTheme').onclick=toggleTheme;$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');if(localStorage.nexusTheme==='light')document.body.dataset.theme='light';home();bindGo();
